
= Access Snowflake from Clojure using the `next.jdbc` library

== Overview

https://www.snowflake.com/[Snowflake] is a cloud database platform that not only allows you to store
& query your own data, but is also a data marketplace where you can buy & sell data from 3rd
parties.

From Clojure, we can interact with Snowflake via JDBC Java interop using the 
https://github.com/seancorfield/next-jdbc[next.jdbc] library.

== Setup

Make sure you have Java, Leiningen, and Clojure installed:

```
~ > java --version
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9)
OpenJDK 64-Bit Server VM (build 11.0.10+9, mixed mode)
~ >
~ >
~ > lein --version
Leiningen 2.9.6 on Java 11.0.10 OpenJDK 64-Bit Server VM
```

=== WARNING: You must user Java 11

As of this writing (Oct 2021), the Snowflake JDBC driver has a bug that crashes if you use a newer
version of Java (eg Java 17).


== Installation 

This code uses the `lein-environ` plugin to access your Snowflake credentials from 
a file `profiles.clj` which you should **never check into SCM/git**.
After using `git clone` to copy this repo to your local machine, execute:

    > cp profiles-template.clj profiles.clj     # copy template file to actual file

Then, in `profiles.clj`, replace the placeholders `XXXXX` and `YYYYY` 
with the actual values for your Snowflake `user` and `password`.

